Upgrade JsonRpcSharp & Nethereum (to only-NetStandard version)
The change was done so that we didn't have different sub-dependencies
anymore depending on .NET4x or .NETStandard (e.g. the typical dichotomy
of Portable.BouncyCastle vs BouncyCastle).

The upgrade from 4.6.1 to 4.7.1 is done so that xbuild can compile
.NET4.x projects against .NetStandard libs, otherwise it would fail
with:
/builds/nblockchain/geewallet/src/GWallet.Backend/Ether/EtherServer.fs(515,35): error FS1108: The type 'Object' is required here and is unavailable. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
(But msbuild doesn't fail, surprisingly.)

The RpcClient->HttpClient rename is because of this:
https://github.com/nblockchain/JsonRpcSharp/commit/fb4a73a6e71cc60793bbbe7e4aa70e1aba6bdb7e

The upgrade script (especially useful for the frontend branch) is:
$ ./scripts/replace.fsx 0.91.0-date20200508-0436.git-69b4b96 0.92.0-date20200610-0657.git-425436f
$ ./scripts/replace.fsx 0.91.0-date20200508-0551.git-e09a8a1 0.92.0-date20200610-0232.git-686865c

And I've had to add again the bouncyCastle reference back (essentially
reverting d7de449c8ea0a9e5433189b84de1b6185774c087) because otherwise we
would get this crash at runtime:

[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeInitializationException: The type initializer for '<StartupCode$GWallet-Backend>.$EtherAccount' threw an exception. ---> System.TypeLoadException: Could not load type of field 'Nethereum.KeyStore.Crypto.RandomBytesGenerator:Random' (0) due to: Could not load file or assembly 'BouncyCastle.Crypto, Version=1.8.2.0, Culture=neutral, PublicKeyToken=0e99375e54769942' or one of its dependencies.
  at Nethereum.KeyStore.KeyStorePbkdf2Service..ctor () [0x00000] in <ac67d0374e064939bf308bac5623de8e>:0
  at Nethereum.KeyStore.KeyStoreService..ctor () [0x00011] in <ac67d0374e064939bf308bac5623de8e>:0
  at <StartupCode$GWallet-Backend>.$EtherAccount..cctor () [0x00018] in /Users/knocte/Documents/Code/geewalletMASTER/src/GWallet.Backend/Ether/EtherAccount.fs:23
   --- End of inner exception stack trace ---
  at (wrapper managed-to-native) System.Object.__icall_wrapper_mono_generic_class_init(intptr)
  at GWallet.Backend.Ether.Account.GetPublicAddressFromNormalAccountFile (GWallet.Backend.FileRepresentation accountFile) [0x0000d] in /Users/knocte/Documents/Code/geewalletMASTER/src/GWallet.Backend/Ether/EtherAccount.fs:30
  at GWallet.Backend.Account+fromAccountFileToPublicAddress@79-1.Invoke (GWallet.Backend.FileRepresentation accountFile) [0x00000] in /Users/knocte/Documents/Code/geewalletMASTER/src/GWallet.Backend/Account.fs:79
  at GWallet.Backend.BaseAccount..ctor (GWallet.Backend.Currency currency, GWallet.Backend.FileRepresentation accountFile, Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] fromAccountFileToPublicAddress) [0x00016] in /Users/knocte/Documents/Code/geewalletMASTER/src/GWallet.Backend/AccountTypes.fs:47
  at GWallet.Backend.NormalAccount..ctor (GWallet.Backend.Currency currency, GWallet.Backend.FileRepresentation accountFile, Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] fromAccountFileToPublicAddress) [0x00000] in /Users/knocte/Documents/Code/geewalletMASTER/src/GWallet.Backend/AccountTypes.fs:52
  at GWallet.Backend.Account+GetAllActiveAccounts@54.GenerateNext (System.Collections.Generic.IEnumerable`1[GWallet.Backend.IAccount]& next) [0x00235] in /Users/knocte/Documents/Code/geewalletMASTER/src/GWallet.Backend/Account.fs:80
  at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1[T].MoveNextImpl () [0x00016] in E:\A\_work\130\s\src\fsharp\FSharp.Core\seqcore.fs:371
  at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1[T].System-Collections-IEnumerator-MoveNext () [0x00000] in E:\A\_work\130\s\src\fsharp\FSharp.Core\seqcore.fs:403
  at Microsoft.FSharp.Collections.Internal+IEnumerator+map@75[b,a].DoMoveNext (b& curr) [0x00000] in E:\A\_work\130\s\src\fsharp\FSharp.Core\seq.fs:77
  at Microsoft.FSharp.Collections.Internal+IEnumerator+MapEnumerator`1[T].System-Collections-IEnumerator-MoveNext () [0x0000b] in E:\A\_work\130\s\src\fsharp\FSharp.Core\seq.fs:64
  at System.Collections.Generic.List`1[T].AddEnumerable (System.Collections.Generic.IEnumerable`1[T] enumerable) [0x00059] in <55adae4546cd485ba70e2948332ebe8c>:0
  at System.Collections.Generic.List`1[T]..ctor (System.Collections.Generic.IEnumerable`1[T] collection) [0x00062] in <55adae4546cd485ba70e2948332ebe8c>:0
  at Microsoft.FSharp.Collections.SeqModule.ToArray[T] (System.Collections.Generic.IEnumerable`1[T] source) [0x00064] in E:\A\_work\130\s\src\fsharp\FSharp.Core\seq.fs:823
  at <StartupCode$FSharp-Core>.$Async+Parallel@1175[T].Invoke (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt) [0x00000] in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:1178
--- End of stack trace from previous location where exception was thrown ---

  at GWallet.Backend.Infrastructure.Report[a] (System.Exception ex, SharpRaven.Data.ErrorLevel _arg1) [0x00019] in /Users/knocte/Documents/Code/geewalletMASTER/src/GWallet.Backend/Infrastructure.fs:69
  at GWallet.Backend.Infrastructure.ReportCrash[a] (System.Exception ex) [0x00000] in /Users/knocte/Documents/Code/geewalletMASTER/src/GWallet.Backend/Infrastructure.fs:82
  at Program.NormalStartWithNoParameters () [0x00017] in /Users/knocte/Documents/Code/geewalletMASTER/src/GWallet.Frontend.Console/Program.fs:379
  at Program.main (System.String[] argv) [0x0002b] in /Users/knocte/Documents/Code/geewalletMASTER/src/GWallet.Frontend.Console/Program.fs:397
  at GWallet.Backend.Infrastructure.Report[a] (System.Exception ex, SharpRaven.Data.ErrorLevel _arg1) [0x00019] in /Users/knocte/Documents/Code/geewalletMASTER/src/GWallet.Backend/Infrastructure.fs:69
  at GWallet.Backend.Infrastructure.ReportCrash[a] (System.Exception ex) [0x00000] in /Users/knocte/Documents/Code/geewalletMASTER/src/GWallet.Backend/Infrastructure.fs:82
  at GWallet.Backend.Infrastructure.OnUnhandledException[a] (System.Object _arg1, System.UnhandledExceptionEventArgs args) [0x00002] in /Users/knocte/Documents/Code/geewalletMASTER/src/GWallet.Backend/Infrastructure.fs:85
  at GWallet.Backend.Infrastructure+SetupSentryHook@88-4.Invoke (System.Object delegateArg0, System.UnhandledExceptionEventArgs delegateArg1) [0x00000] in /Users/knocte/Documents/Code/geewalletMASTER/src/GWallet.Backend/Infrastructure.fs:88